name: flutter_pusher_compatible_client
description: Pusher Protocol Compatible Client for Flutter
version: 2.0.1
homepage: https://github.com/pusher/pusher-channels-flutter
repository: https://github.com/pusher/pusher-channels-flutter
issue_tracker: https://github.com/pusher/pusher-channels-flutter/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: dev.stayallive.channels_flutter
        pluginClass: PusherChannelsFlutterPlugin
        fileName: pusher_channels_flutter.dart
      ios:
        pluginClass: PusherChannelsFlutterPlugin
      web:
        pluginClass: PusherChannelsFlutterWeb
        fileName: pusher_channels_flutter_web.dart
